-- MySQL Script generated by MySQL Workbench
-- Mon Dec 16 23:42:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mural_eventos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mural_eventos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mural_eventos` DEFAULT CHARACTER SET utf8 ;
USE `mural_eventos` ;

-- -----------------------------------------------------
-- Table `mural_eventos`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mural_eventos`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(1000) NULL,
  `email` VARCHAR(1000) NULL,
  `senha` VARCHAR(200) NULL,
  `tipo_usuario` ENUM('admin', 'user') NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mural_eventos`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mural_eventos`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(500) NULL,
  `descricao` LONGTEXT NULL,
  `data_evento` DATE NULL,
  `hora_evento` TIME NULL,
  `banner_url` VARCHAR(300) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Usuario_idx` (`Usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_Evento_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mural_eventos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mural_eventos`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mural_eventos`.`Comentario` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `conteudo` LONGTEXT NULL,
  `data_hora_comentario` DATETIME NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_Comentario_Usuario1_idx` (`Usuario_idUsuario` ASC) ,
  INDEX `fk_Comentario_Evento1_idx` (`Evento_idEvento` ASC) ,
  CONSTRAINT `fk_Comentario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mural_eventos`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mural_eventos`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
